theme = "catppuccin_mocha"

[editor]
line-number = "relative"
cursorline = true
bufferline = "multiple"
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

# [editor.whitespace.render]
# tab = "all"
# newline = "all"

# [editor.whitespace.characters]
# space = "·"
# nbsp = "⍽"
# tab = "→"
# newline = "↵"
# tabpad = "·" # Tabs will look like "→···" (depending on tab width)

[editor.statusline]
left = ["mode", "separator", "file-name", "file-modification-indicator", "diagnostics"]
center = ["read-only-indicator"]
right = ["selections" ,"file-encoding", "position"]
separator = " "

[keys.normal]
"space" = { "s" = ":w", "S" = ":lsp-restart", "k" = ":buffer-close", "Q" = ":q!", "l" = { "f" = ":format", "a" = "code_action" ,"s" = "symbol_picker", "w" = { "s" = "workspace_symbol_picker" }, "g" = "hover" } }
"esc" = ["collapse_selection", "keep_primary_selection"]
