theme = "catppuccin_mocha"

[editor]
line-number = "relative"
cursorline = true
bufferline = "multiple"
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "separator", "file-name", "diagnostics"]
center = ["read-only-indicator"]
right = ["spinner", "file-encoding", "position"]
separator = " "

[keys.normal]
"space" = { "s" = ":w", "l" = { "f" = ":format", "s" = "symbol_picker", "g" = "hover" }, "k" = ":buffer-close", "q" = ":q", "Q" = ":q!" }
"esc" = ["collapse_selection", "keep_primary_selection"]
