theme = "catppuccin_mocha"

[editor]
auto-pairs = false # Hot take 
line-number = "relative"
cursorline = true
bufferline = "multiple"
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.statusline]
left = ["mode", "separator", "file-name", "file-modification-indicator", "diagnostics"]
center = ["version-control"]
right = ["read-only-indicator","file-encoding", "position"]
separator = " "

[keys.normal]
"space" = { "s" = ":w", "S" = ":lsp-restart", "k" = ":buffer-close", "Q" = ":q!", "l" = { "f" = ":format", "a" = "code_action" ,"s" = "symbol_picker", "w" = { "s" = "workspace_symbol_picker" }, "g" = "hover" } }
"esc" = ["collapse_selection", "keep_primary_selection"]
