# https://github.com/helix-editor/helix/blob/master/languages.toml for configs
# https://github.com/helix-editor/helix/wiki/How-to-install-the-default-language-servers for how to install lang servers

[[language]]
name = "python"
auto-format = false
formatter = { command = "black", args = ["--line-length", "160", "--quiet", "-"] }
language-servers = ["pyright"]


