# https://github.com/helix-editor/helix/blob/master/languages.toml for configs

[[language]]
name = "python"
auto-format = false
formatter = { command = "black", args = ["--line-length", "160", "--quiet", "-"] }
language-servers = ["pyright"]


