
env:
  # TERM env customization.
  #
  # If this property is not set, alacritty will set it to xterm-256color.
  #
  # Note that some xterm terminfo databases don't declare support for italics.
  # You can verify this by checking for the presence of `smso` and `sitm` in
  # `infocmp xterm-256color`.
  TERM: xterm-256color



colors:

 # Default colors
  primary:
    background: '0x1f2022'
    foreground: '0xebebeb'

  # Colors the cursor will use if `custom_cursor_colors` is true
  # cursor:
  #   text: '0xebebeb'
  #   cursor: '0xbd002c'

  # Normal colors
  normal:
    black:   '0x1f2022'
    red:     '0xf2241f'
    green:   '0x67b11d'
    yellow:  '0xb1951d'
    blue:    '0x4f97d7'
    magenta: '0xa31db1'
    cyan:    '0x2d9574'
    white:   '0xa3a3a3'

  # Bright colors
  bright:
    black:   '0x585858'
    red:     '0xf2241f'
    green:   '0x67b11d'
    yellow:  '0xb1951d'
    blue:    '0x4f97d7'
    magenta: '0xa31db1'
    cyan:    '0x2d9574'
    white:   '0xf8f8f8'

  indexed_colors:
    - { index: 16, color: '0xffa500' }
    - { index: 17, color: '0xb03060' }
    - { index: 18, color: '0x282828' }
    - { index: 19, color: '0x444155' }
    - { index: 20, color: '0xb8b8b8' }
    - { index: 21, color: '0xe8e8e8' }

# Background opacity
window:
  opacity: 0.9


font:
  # Normal (roman) font face
  size: 13.0
  normal:
    # Font family
    #
    # Default:
    #   - (macOS) Menlo
    #   - (Linux) monospace
    #   - (Windows) Consolas
    family: 'Fira Code'

    # The `style` can be specified to pick a specific face.
    style: Regular

scrolling:
  # How many lines of scrollback to keep,
  # '0' will disable scrolling.
  history: 10000

  # Number of lines the viewport will move for every line
  # scrolled when scrollback is enabled (history > 0).
  multiplier: 3

  # Faux Scrolling
  #
  # The `faux_multiplier` setting controls the number
  # of lines the terminal should scroll when the alternate
  # screen buffer is active. This is used to allow mouse
  # scrolling for applications like `man`.
