""""""""""""""""""""""
"""""" LEADER KEY:
""""""""""""""""""""""
map <SPACE> <Leader>

""""""""""""""""""""""
"""""" SETTINGS:
""""""""""""""""""""""

" if hidden is not set, TextEdit might fail.
set hidden

" Some servers have issues with backup files, see #649
set nobackup
set nowritebackup
set showcmd

set updatetime=100

" don't give |ins-completion-menu| messages.
set shortmess+=c

" always show signcolumns
set signcolumn=yes

syntax enable
set nocompatible

"Color theme
set background=dark
colorscheme slate

"indentation
set tabstop=4
set softtabstop=4
set shiftwidth=4
set noexpandtab
set smartindent
set smartcase

" line numbers and tabs
set number relativenumber
set nu rnu 
set completeopt-=preview
set guioptions-=e
set sessionoptions+=tabpages,globals

" directory navigations and settings
set foldenable
set incsearch
set nohlsearch
set showmatch
set wildmenu
set cursorline
set noswapfile
set tags=tags
set bs=2
set mouse=a
set clipboard=unnamedplus
set laststatus=2
set t_Co=256


" MODE SPECIFIC SETTINGS:
autocmd FileType html setlocal ts=2 sts=2 sw=2
autocmd FileType css setlocal ts=2 sts=2 sw=2
autocmd FileType javascript setlocal ts=2 sts=2 sw=2
autocmd FileType jsx setlocal ts=2 sts=2 sw=2
autocmd FileType typescript setlocal ts=2 sts=2 sw=2
autocmd FileType tsx setlocal ts=2 sts=2 sw=2

" Don't offer to open certain files/directories
set wildignore+=*.bmp,*.gif,*.ico,*.jpg,*.png,*.ico
set wildignore+=*.pdf,*.psd
set wildignore+=node_modules/*,bower_components/*
set wildignore+=*/tmp/*,*.so,*.swp,*.zip     " MacOSX/Linux

" Search down into subfolders
" Provides tab-completion for all file-related tasks
set path+=**

" grep arg
set grepprg=grep\ -HRIn\ $*\ .

"" NETRW:
let g:netrw_banner=0 " Disable annoying banner
let g:netrw_browse_split=4 " open in prior window
let g:netrw_altv=1          " open splits to the right
let g:netrw_liststyle=3     " tree view
let g:netrw_winsize = 25    " take 25 % of window
let g:netrw_list_hide=netrw_gitignore#Hide()
let g:netrw_list_hide.=',\(^\|\s\s\)\zs\.\S\+'
let g:NetrwIsOpen=0

function! ToggleNetrw()
    if g:NetrwIsOpen
        let i = bufnr("$")
        while (i >= 1)
            if (getbufvar(i, "&filetype") == "netrw")
                silent exe "bwipeout " . i 
            endif
            let i-=1
        endwhile
        let g:NetrwIsOpen=0
    else
        let g:NetrwIsOpen=1
        silent Lexplore
    endif
endfunction

noremap <silent> <leader>ut :call ToggleNetrw()<CR>

"""""""""""""""""""""""
""""" PERSONAL BINDINGS:
"""""""""""""""""""""""

nnoremap <leader>cn :noh<CR>
nnoremap Y y$
nnoremap <leader>s :w<CR>
nnoremap <leader>k :bd<CR>
nnoremap <leader>x :tabclose<CR>
nnoremap <leader>q :q<CR>
nnoremap <leader>Q :q!<CR>
nnoremap <leader>f :e 

nnoremap <leader>cs :terminal<CR>
nnoremap <leader>ca :%s/<C-r><C-w>/<C-r><C-w>/g<Left><Left>
nnoremap <leader>cA :%s/<C-r><C-a>/<C-r><C-a>/g<Left><Left>
nnoremap <leader>cm *Ncgn
nnoremap <leader>ci :%s/\<<C-r><C-w>\>/<C-r><C-w>/gI<Left><Left><Left>
nnoremap <leader>/ :grep
nnoremap <leader>* :grep! "\b<C-R><C-W>\b"<CR>:cw<CR>
nnoremap <leader>ux :!chmod +x %<CR>
nnoremap <leader>uc :!


nnoremap ]q :cnext<CR>
nnoremap [q :cprev<CR>


nnoremap <leader>a <C-^>
nnoremap <leader>bn :bnext<CR>
nnoremap <leader>bp :bprevious<CR>


nnoremap <leader>tn :tabnext<CR>
nnoremap <leader>tp :tabprevious<CR>

"""""""""""""""""""""""
""""" WINDOW MANAGEMENT:
"""""""""""""""""""""""
" Fix splitting
set splitbelow splitright
