# ==========================================
# Appearance
# ==========================================

# Theme
include current-theme.conf

# Typography
font_size        16.0
font_family      JetBrainsMono Nerd Font

# Cursor Tuning
cursor_shape          block
cursor_blink_interval 0
cursor                #FFAE42
shell_integration     no-cursor
enable_audio_bell False

# Window Aesthetics
background_opacity 0.9
window_padding_width 5

# ==========================================
# Bindings & Window Management
# ==========================================

enabled_layouts splits,stack

# Mappings for your leader key chord (ctrl + ,)
map ctrl+,>z       toggle_layout stack
map ctrl+,>shift+f toggle_fullscreen
map ctrl+,>c       launch --type=tab --cwd=current
map ctrl+,>shift+\ launch --location=vsplit --cwd=current
map ctrl+,>minus   launch --location=hsplit --cwd=current

## Movement
map ctrl+,>h neighboring_window left
map ctrl+,>j neighboring_window down
map ctrl+,>k neighboring_window up
map ctrl+,>l neighboring_window right

map ctrl+,>1 goto_tab 1
map ctrl+,>2 goto_tab 2
map ctrl+,>3 goto_tab 3
map ctrl+,>4 goto_tab 4

map ctrl+,>p previous_tab
map ctrl+,>n next_tab

## Closing, Quitting
map ctrl+,>x       close_window
map ctrl+,>shift+k close_tab
map ctrl+,>shift+q quit
